<Project>
  <Import Project="Local.props" Condition="Exists('Local.props')" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <DuckovFolder Condition=" '$(DuckovFolder)' == '' AND '$(SteamFolder)' != '' ">$(SteamFolder)steamapps/common/Escape from Duckov/</DuckovFolder>
    <ModsDirectory>$(DuckovFolder)Duckov_Data/Mods/</ModsDirectory>
    <ManagedDirectory>$(DuckovFolder)Duckov_Data/Managed/</ManagedDirectory>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>
  <!-- Fail early if SteamFolder is not provided -->
  <Target Name="FailIfSteamFolderMissing" BeforeTargets="PrepareForBuild;Restore" Condition="'$(CI)' != 'true'">
    <Error Text="SteamFolder property must be set. Provide it via Local.props or -p:SteamFolder=/path/to/steam/"
           Condition="'$(SteamFolder)' == ''" />
  </Target>
</Project>
